theme: jekyll-theme-minimal
generator_amp:
    templateDir: amp-template
    assetDistDir: amp-dist
    logo:
        path: エラー画面 (1).png 
        width: 1366
        height: 768
    warningLog: false
